const crypto = require('crypto');
const SESSION_MS = 15 * 60 * 1000;
const seed = [
  ['student@mdu.edu','Alex Smith','student','Computer Science · Year 3','JBSWY3DPEHPK3PXP'],
  ['lecturer@mdu.edu','Dr. Maya Chen','lecturer','School of Computing','KRSXG5DSNFXGOIDB'],
  ['admin@mdu.edu','Jordan Bennett','admin','MDU IT Services','MFRGGZDFMZTWQ2LK']
];
const hash = p => crypto.scryptSync(p, 'mdu-demo-salt', 32).toString('hex');
const token = (n=32) => crypto.randomBytes(n).toString('base64url');
const secret = () => Array.from(crypto.randomBytes(20),b=>'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'[b&31]).join('');
const b32 = s => { let bits=''; for(const c of s.replace(/[=\s-]/g,'').toUpperCase()){const i='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'.indexOf(c);if(i<0)throw Error('Invalid authenticator secret');bits+=i.toString(2).padStart(5,'0')}return Buffer.from((bits.match(/.{8}/g)||[]).map(x=>parseInt(x,2))); };
const totp = (s,time=Math.floor(Date.now()/1000)) => {const q=Buffer.alloc(8);q.writeBigUInt64BE(BigInt(Math.floor(time/30)));const d=crypto.createHmac('sha1',b32(s)).update(q).digest(),o=d[19]&15;return String((d.readUInt32BE(o)&0x7fffffff)%1e6).padStart(6,'0')};
const validTotp = (s,c) => /^\d{6}$/.test(c||'') && [-30,0,30].some(x=>crypto.timingSafeEqual(Buffer.from(totp(s,Math.floor(Date.now()/1000)+x)),Buffer.from(c)));
const cookies = req => Object.fromEntries((req.headers.cookie||'').split(';').map(x=>x.trim().split('=').map(decodeURIComponent)).filter(x=>x[0]));
const cookie = (res,n,v,age=SESSION_MS/1000) => res.setHeader('Set-Cookie',`${n}=${encodeURIComponent(v)}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=${age}`);
const body = req => new Promise((ok,bad)=>{let x='';req.on('data',c=>x+=c);req.on('end',()=>{try{ok(JSON.parse(x||'{}'))}catch{bad(Error('Invalid request'))}})});

module.exports = async (req,res) => {
  const origin=req.headers.origin; res.setHeader('Cache-Control','no-store'); if(origin){res.setHeader('Access-Control-Allow-Origin',origin);res.setHeader('Access-Control-Allow-Credentials','true');res.setHeader('Vary','Origin')}
  if(req.method==='OPTIONS'){res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type,X-CSRF-Token');return res.status(204).end()}
  const url=new URL(req.url,'https://portal.local'), path=url.pathname;
  const json=(s,x)=>{res.statusCode=s;res.setHeader('Content-Type','application/json; charset=utf-8');return res.end(JSON.stringify(x))};
  const key=process.env.SUPABASE_SERVICE_ROLE_KEY, base=process.env.SUPABASE_URL;
  if(!key||!base)return json(500,{error:'Server configuration is incomplete. Add Supabase environment variables in Vercel.'});
  const db=async(p,opt={})=>{const r=await fetch(base+'/rest/v1/'+p,{...opt,headers:{apikey:key,Authorization:`Bearer ${key}`,Accept:'application/json','Content-Type':'application/json',Prefer:opt.prefer||'return=representation',...(opt.headers||{})}});const t=await r.text();let d;try{d=JSON.parse(t||'null')}catch{d=t}if(!r.ok)throw Error(d.message||d.error||'Database request failed');return d};
  const audit=(type,email,detail='')=>db('mdu_audit_logs',{method:'POST',body:JSON.stringify({type,email,detail})}).catch(()=>{});
  const bootstrap=async()=>{const rows=await db('mdu_users?select=email&limit=1');if(rows.length)return;await db('mdu_users',{method:'POST',body:JSON.stringify(seed.map(([email,name,role,department,totp_secret])=>({email,name,role,department,totp_secret,password_hash:hash('Password123!'),active:true})))});};
  const session=async(requireMfa=true)=>{const id=cookies(req).mdu_session;if(!id)throw Error('Your secure session has expired. Please sign in again.');const r=await db(`mdu_sessions?id=eq.${encodeURIComponent(id)}&select=*`);const s=r[0];if(!s||new Date(s.expires_at)<new Date()||(requireMfa&&!s.verified))throw Error('Your secure session has expired. Please sign in again.');await db(`mdu_sessions?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify({expires_at:new Date(Date.now()+SESSION_MS).toISOString()})});return {...s,id};};
  const admin=async()=>{const s=await session();const u=(await db(`mdu_users?email=eq.${encodeURIComponent(s.email)}&select=*`))[0];if(!u||u.role!=='admin')throw Error('Administrator access required.');return {s,u};};
  const protect=async fn=>{try{await bootstrap();return await fn()}catch(e){return json(e.message.includes('required')?403:401,{error:e.message||'Unable to process request'})}};
  try {
    if(req.method==='GET'&&path==='/api/health')return json(200,{ok:true,backend:'supabase',sessionTimeoutMinutes:15});
    if(req.method==='POST'&&path==='/api/login')return protect(async()=>{const {email,password}=await body(req),mail=String(email||'').toLowerCase(),u=(await db(`mdu_users?email=eq.${encodeURIComponent(mail)}&select=*`))[0];if(!u||!u.active||!crypto.timingSafeEqual(Buffer.from(hash(String(password||'')),'hex'),Buffer.from(u.password_hash,'hex'))){await audit('FAILED_LOGIN',mail,'Invalid credentials');return json(401,{error:'Invalid email or password.'})}const id=token(),csrf=token(24);await db('mdu_sessions',{method:'POST',body:JSON.stringify({id,email:mail,csrf,verified:false,expires_at:new Date(Date.now()+SESSION_MS).toISOString()})});cookie(res,'mdu_session',id);await audit('LOGIN_PASSWORD_VERIFIED',mail,'Awaiting TOTP');return json(200,{requiresMfa:true,profile:{email:mail,name:u.name,role:u.role},setup:{issuer:'Metropolitan Digital University',account:mail,secret:u.totp_secret,otpauth:`otpauth://totp/MDU%20Portal:${encodeURIComponent(mail)}?secret=${u.totp_secret}&issuer=Metropolitan%20Digital%20University&algorithm=SHA1&digits=6&period=30`}})});
    if(req.method==='POST'&&path==='/api/verify-totp')return protect(async()=>{const s=await session(false),{code}=await body(req),u=(await db(`mdu_users?email=eq.${encodeURIComponent(s.email)}&select=*`))[0];if(!validTotp(u.totp_secret,String(code||''))){await audit('FAILED_MFA',s.email,'Invalid TOTP');return json(401,{error:'Incorrect authentication code. Try the current code in your app.'})}const csrf=token(24);await db(`mdu_sessions?id=eq.${encodeURIComponent(s.id)}`,{method:'PATCH',body:JSON.stringify({verified:true,csrf})});await audit('MFA_VERIFIED',s.email,'Google Authenticator TOTP verified');return json(200,{profile:{email:u.email,name:u.name,role:u.role,department:u.department},csrf,expiresIn:SESSION_MS})});
    if(req.method==='GET'&&path==='/api/users')return protect(async()=>{await admin();return json(200,{users:await db('mdu_users?select=email,name,role,department,active&order=role,name')})});
    if(req.method==='GET'&&path==='/api/audit')return protect(async()=>{await admin();return json(200,{rows:await db('mdu_audit_logs?select=created_at,type,email,detail&order=created_at.desc&limit=100')})});
    if(req.method==='POST'&&path==='/api/users')return protect(async()=>{const {s}=await admin();if(req.headers['x-csrf-token']!==s.csrf)return json(403,{error:'CSRF validation failed.'});const {name,email,role,department,password}=await body(req),mail=String(email||'').trim().toLowerCase();if(!name||!/^[^\s@]+@mdu\.edu$/i.test(mail)||!['student','lecturer','admin'].includes(role)||String(password||'').length<10)return json(400,{error:'Enter a name, @mdu.edu email, role, and a password with at least 10 characters.'});const existing=await db(`mdu_users?email=eq.${encodeURIComponent(mail)}&select=email`);if(existing.length)return json(409,{error:'An account with this email already exists.'});const u={email:mail,name:String(name).trim(),role,department:String(department||'MDU Community').trim(),active:true,totp_secret:secret(),password_hash:hash(password)};await db('mdu_users',{method:'POST',body:JSON.stringify(u)});await audit('USER_CREATED',s.email,`${role} account created: ${mail}`);return json(201,{user:{email:mail,name:u.name,role,department:u.department,active:true}})});
    if(req.method==='POST'&&path==='/api/users/action')return protect(async()=>{const {s}=await admin();if(req.headers['x-csrf-token']!==s.csrf)return json(403,{error:'CSRF validation failed.'});const {email,action,name,department,role}=await body(req),mail=String(email||'').toLowerCase(),u=(await db(`mdu_users?email=eq.${encodeURIComponent(mail)}&select=*`))[0];if(!u)return json(404,{error:'User not found.'});if(mail===s.email&&['toggle','delete'].includes(action))return json(400,{error:'You cannot disable or delete your own account.'});if(action==='delete'){await db(`mdu_users?email=eq.${encodeURIComponent(mail)}`,{method:'DELETE'});await audit('USER_DELETED',s.email,mail);return json(200,{message:'User account deleted and active sessions revoked.'})}if(action==='toggle'){u.active=!u.active;await audit(u.active?'ACCOUNT_ENABLED':'ACCOUNT_DISABLED',s.email,mail)}else if(action==='reset'){u.password_hash=hash('Password123!');u.totp_secret=secret();await audit('PASSWORD_RESET',s.email,`${mail}; MFA secret rotated`)}else if(action==='update'){if(!String(name||'').trim()||!String(department||'').trim()||!['student','lecturer','admin'].includes(role))return json(400,{error:'Enter a valid name, department, and role.'});if(mail===s.email&&role!=='admin')return json(400,{error:'You cannot remove your own administrator role.'});u.name=String(name).trim();u.department=String(department).trim();u.role=role;await audit('USER_UPDATED',s.email,`${mail}; role set to ${role}`)}else return json(400,{error:'Unsupported user action.'});await db(`mdu_users?email=eq.${encodeURIComponent(mail)}`,{method:'PATCH',body:JSON.stringify({name:u.name,role:u.role,department:u.department,active:u.active,totp_secret:u.totp_secret,password_hash:u.password_hash})});return json(200,{message:action==='reset'?'Password reset to Password123! and MFA enrollment reset.':action==='update'?'User profile updated.':`Account ${u.active?'enabled':'disabled'}.`})});
    if(req.method==='POST'&&path==='/api/logout')return protect(async()=>{const s=await session();if(req.headers['x-csrf-token']!==s.csrf)return json(403,{error:'CSRF validation failed.'});await db(`mdu_sessions?id=eq.${encodeURIComponent(s.id)}`,{method:'DELETE'});cookie(res,'mdu_session','',0);await audit('LOGOUT',s.email,'User logout');return json(200,{ok:true})});
    return json(404,{error:'Not found'});
  } catch(e) { return json(500,{error:e.message||'Server error'}); }
};
